"""
Action Plan Schema for Layer 2 Agent Output

Defines structured output format for Agent decisions to enable:
1. Layer 3 Dashboard rendering
2. Layer 4 Auto-remediation execution
3. Human-in-the-loop (HITL) approval gates

Related: ADR-002 Structured Output Decision
"""
from typing import List, Literal
from pydantic import BaseModel, Field


class ActionStep(BaseModel):
    """
    Represents a single action step in the diagnosis process

    Attributes:
        step_id: Sequential step identifier
        description: Human-readable description of what this step does
        action_type: Type of action (k8s_exec, query, verify)
        target: Target system/service for the action
        command: Actual command to execute
        is_destructive: Whether this action modifies system state (triggers HITL)
    """
    step_id: int = Field(..., description="Sequential step ID", ge=1)
    description: str = Field(..., description="Human-readable step description")
    action_type: Literal["k8s_exec", "query", "verify"] = Field(
        ...,
        description="Type of action: k8s_exec (Kubernetes command), query (read-only query), verify (validation check)"
    )
    target: str = Field(..., description="Target container/service/endpoint")
    command: str = Field(..., description="Command to execute")
    is_destructive: bool = Field(
        default=False,
        description="True if action modifies state (requires human approval)"
    )

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "step_id": 1,
                    "description": "Check nginx error logs",
                    "action_type": "query",
                    "target": "nginx-pod",
                    "command": "kubectl logs nginx-pod --tail=100",
                    "is_destructive": False
                },
                {
                    "step_id": 2,
                    "description": "Restart nginx service",
                    "action_type": "k8s_exec",
                    "target": "nginx-deployment",
                    "command": "kubectl rollout restart deployment/nginx",
                    "is_destructive": True
                }
            ]
        }


class ActionPlan(BaseModel):
    """
    Complete action plan generated by Layer 2 Agent

    Attributes:
        root_cause: Identified root cause of the anomaly
        confidence_score: Agent's confidence in the diagnosis (0.0-1.0)
        actions: List of ordered action steps
    """
    root_cause: str = Field(..., description="Root cause analysis summary")
    confidence_score: float = Field(
        ...,
        description="Confidence level in diagnosis",
        ge=0.0,
        le=1.0
    )
    actions: List[ActionStep] = Field(
        default_factory=list,
        description="Ordered list of action steps"
    )

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "root_cause": "Connection pool exhaustion in nginx due to backend timeout",
                    "confidence_score": 0.85,
                    "actions": [
                        {
                            "step_id": 1,
                            "description": "Verify connection pool status",
                            "action_type": "query",
                            "target": "nginx-1",
                            "command": "netstat -an | grep ESTABLISHED | wc -l",
                            "is_destructive": False
                        },
                        {
                            "step_id": 2,
                            "description": "Reload nginx to clear connection pool",
                            "action_type": "k8s_exec",
                            "target": "nginx-deployment",
                            "command": "kubectl exec nginx-1 -- nginx -s reload",
                            "is_destructive": True
                        }
                    ]
                }
            ]
        }
